version: '3.8'

services:
  # Local PostgreSQL Database
  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: medical_booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: localdev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d medical_booking"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Local n8n Workflow Engine
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=localdev123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=database
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=medical_booking
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=localdev123
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/New_York
    ports:
      - "5678:5678"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
      - ./n8n/config/.env:/home/node/.n8n/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Local Web Application
  webapp:
    build: ./webapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VAPI_API_KEY=${VAPI_API_KEY}
      - VAPI_AGENT_ID=${VAPI_AGENT_ID}
      - DATABASE_URL=postgresql://admin:localdev123@database:5432/medical_booking
      - N8N_URL=http://localhost:5678
      - N8N_USER=admin
      - N8N_PASSWORD=localdev123
    depends_on:
      - database
      - n8n
    volumes:
      - ./webapp:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  n8n_data: 